name: Ejecutar Clima automáticamente

on:
  schedule:
    - cron: "0 */2 * * *"   # cada 2 horas
  workflow_dispatch:         # ejecución manual

jobs:
  run-clima:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pynasapower

      - name: Ejecutar script
        run: python run.py
