name: Ejecutar Clima automáticamente

on:
  schedule:
    # Ejemplo: todos los días a las 00:00 UTC
    - cron: "0 */2 * * *"
  workflow_dispatch:  # para permitir ejecutar manualmente desde GitHub
jobs:
  run-clima:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # o la versión que uses

      - name: Instalar dependencias (si tienes requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecutar script
        run: python run.py
